apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ms
  labels:
    app: user-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms
    spec:
      containers:
        - name: user-ms
          image: islamahmad/eaproj-userms:1.0.13
          env:
            - name: APP_VERSION
              value: "islamahmad/eaproj-userms:1.0.13"
            - name: MYSQL_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: user-ms
                 key: MYSQL_PASSWORD
            # GENERAL
            - name: SERVER_PORT
              value: "8080"
#           - name: MYSQL_PORT
#             valueFrom:
#               configMapKeyRef:
#                 name: user-ms
#                 key: MYSQL_PORT
#           - name: MYSQL_USER
#             valueFrom:
#               configMapKeyRef:
#                 name: user-ms
#                 key: MYSQL_USER
#           - name: MYSQL_HOST
#             valueFrom:
#               configMapKeyRef:
#                 name: user-ms
#                 key: MYSQL_HOST
#           - name: AUTHENTICATE_SERVICE
          envFrom:
            - configMapRef:
                name: services-global
            - configMapRef:
                name: user-ms