apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ms
  labels:
    app: user-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms
    spec:
      containers:
        - name: user-ms
          image: islamahmad/eaproj-userms:1.0.12
          env:
           - name: MYSQL_PASSWORD
             valueFrom:
               configMapKeyRef:
                 name: user-ms
                 key: MYSQL_PASSWORD
           - name: MYSQL_PORT
             valueFrom:
               configMapKeyRef:
                 name: user-ms
                 key: MYSQL_PORT
           - name: MYSQL_USER
             valueFrom:
               configMapKeyRef:
                 name: user-ms
                 key: MYSQL_USER
           - name: MYSQL_HOST
             valueFrom:
               configMapKeyRef:
                 name: user-ms
                 key: MYSQL_HOST
           - name: AUTHENTICATE_SERVICE
             valueFrom:
               configMapKeyRef:
                 name: services-global
                 key: AUTHENTICATE_SERVICE
           - name: DB_NAME
             valueFrom:
               configMapKeyRef:
                 name: user-ms
                 key: DB_NAME