apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ms
  labels:
    app: user-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms
    spec:
      containers:
        - name: user-ms
          image: islamahmad/eaproj-userms:1.0.15
          env:
            - name: APP_VERSION
              value: "islamahmad/eaproj-userms:1.0.15"
            - name: MYSQL_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: user-ms
                 key: MYSQL_PASSWORD
            # GENERAL
            - name: SERVER_PORT
              value: "8080"

          envFrom:
            - configMapRef:
                name: services-global
            - configMapRef:
                name: user-ms